import argparse
from pathlib import Path
import sys

# Add parent directory to path to import afa_py
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from afa_py.afa_config import get_preset_kernel_configs, AFAForwardKernelConfig


def to_map_entry(cfg: AFAForwardKernelConfig) -> str:
    """Convert AFAForwardKernelConfig to C++ map entry string."""
    cpp_cfg = cfg.to_cpp_struct()
    return (
        f"        // {str(cfg)}\n"
        f"        {{{cpp_cfg}, "
        f"&afa_forward_kernel<AFAForwardKernelTraits<{cpp_cfg}>>}},"
    )


def generate_preset_kernels_header(valid_configs: list[AFAForwardKernelConfig]) -> str:
    entries = "\n".join(to_map_entry(cfg) for cfg in valid_configs)
    return f"""#pragma once

#include <map>
#include \"afa_config.cuh\"
#include \"afa_forward_kernel.cuh\"
// Generated by tools/generate_kernels.py

namespace afa {{

typedef void (*forward_kernel_fn)(const AFAForwardParams);

std::map<AFAForwardKernelConfig, forward_kernel_fn>
    forward_kernels = {{
{entries}
    }};

}} // namespace afa
"""


def main(output_path):
    if output_path is None:
        output_path = (
            Path(__file__).resolve().parent.parent / "csrc" / "include" / "afa_preset_kernels.cuh"
        )
    else:
        output_path = Path(output_path)

    # Get preset configs from afa_config.py and filter by additional validation if needed
    preset_configs = get_preset_kernel_configs()
    # Note: get_preset_kernel_configs() already filters by is_valid_config()
    # If additional validation is needed, add it here
    valid_configs = preset_configs
    
    if not valid_configs:
        raise ValueError("No valid kernel configuration is generated.")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_preset_kernels_header(valid_configs))
    print(f"Generated {len(valid_configs)} kernel preset entries to: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="generate_kernels",
        description="Generate include/afa_preset_kernels.cuh based on AFAForwardKernelConfig combinations.",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=False,
        help="Output header path. Default: include/afa_preset_kernels.cuh",
    )
    args = parser.parse_args()
    main(args.output)
